package com.realdolmen.secondjava9app;

import com.realdolmen.firstjava9app.exporting.NumberGenerator;

public class MyCaller {
    public static void main(String[] args) {
        callExportingClazz();
        callNonExportingClazz();
    }

    private static void callExportingClazz() {
        NumberGenerator numberGenerator = new NumberGenerator();
        int generatedNumber = numberGenerator.generateNumber();
        System.out.println("Number generated by firstjava9app = " + generatedNumber);
    }

    private static void callNonExportingClazz() {
        // The line below is not exported, so you won't be able to call it:
//        NonExportingNumberGenerator nonExportingNumberGenerator = new NonExportingNumberGenerator();
    }
}
